### ISSUE TITLE
Issue with Locales Super Table within a Matrix Field

### ISSUE THREAD

**Issue by jonathanhudak** [verbb/super-table#22] opened 2015-07-28 21:40 UTC
Hello,

I'm experiencing an issue when saving an entry's alternate locale. I have a matrix field configuration similar to the one described in the readme of this project under "The Row Layout also shines brightest when using inside a Matrix field as below."

Here are the steps to recreate:
1. Uncheck 'This field is translatable' on the Matrix Field under /Settings/Fields/<matrix field>
2. Go to page to translate. The alternate locale should have a grey cirlce to the right of its title.
3. Save the page with Command+S and the alternate locale should now have a green circle.
4. Click the alternate locale and the matrix fields should be copied over. (this is the only way I've found to copy the matrix fields over from the original locale)
5. _Check 'This field is translatable' on the Matrix Field under /Settings/Fields/<matrix field>
6. Go to page to translate and choose the alternate locale, translate text, and save.
*_Issue*_: Nested SuperTable fields within matrix blocks of the original locale no longer contain their original text content. The alternate locale text *is_ saved though.

I'm running PHP 5.6.11, Apache/2.4.10 (Unix)

Any thoughts to what might be causing the issue? Thanks in advance. This is an awesome plugin.

Jonathan

**Comment by hudakdidit** [comment] 2015-07-28 21:52
Just to follow up, my colleague just pointed out this line https://github.com/engram-design/SuperTable/blob/master/supertable/models/SuperTable_BlockModel.php#L24
"If the SuperTable field is translatable, than each individual block is tied to a single locale, and thus aren't
translatable. Otherwise all blocks belong to all locales, and their content is translatable."

Currently I have the parent matrix field set to translatable thus, from my understanding, making the child super table field also translatable. Could this be the cause of the issue I'm describing? If so, this comment doesn't seem to make sense to me. Shouldn't it be the opposite?

Thanks again.

**Comment by hudakdidit** [comment] 2015-07-28 22:08
Hi once again,
I've just tested this same scenario, but using an un-nested SuperTable field.

Steps:
1. Uncheck 'This field is translatable' on the SuperTable field
2. Create a new entry using that field and command+save.
3. Click the alternate locale for that entry and the field/s and content should be copied over.
4. Check 'This field is translatable' on the SuperTable field
5. Return to the entry, navigate to the alternate locale, edit its text and save.
*Issue* the original locale field has empty values.

So this seems to be a bug. I'd be happy to work on a pull request. If you have any insights into where to address I would be awesome to here.

Thanks again.

**Comment by engram-design** [comment] 2015-07-29 00:22
@hudakdidit Thanks for the extensive summary of your issue - helps a lot! I can confirm this is an issue using either Matrix-SuperTable or SuperTable-Matrix field layout. I cannot seem to replicate this issue when using a SuperTable field (with no Matrix at all), and have tested that this works.

I'll investigate further and let you know. Thanks again!

**Comment by hudakdidit** [comment] 2015-07-29 20:04
@engram-design Thanks for you reply! Yes you're right, I think there was something else at play when I was testing a SuperTable field (with no Matrix at all), it does work properly with locales.

Its seeming like the issue is that when you have a Matrix-SuperTable or SuperTable-Matrix field layout craft isn't able to copy the fields from the original locale to the alternate. My hacky way of duplicating the fields (mentioned above in my original post) is not sustainable with more than 2 locales and was a way of skirting around the actual issue, which is the fields don't copy over.

Since the project I'm working on depends on locales, unfortunately I think I'm going to refactor my layouts without the use of SuperTable. I hope this helps, let me know if you need any help testing when you're able to address this. Thanks man!

**Comment by superflausch** [comment] 2015-11-16 14:54
Any news on this one?

I think I have a related or the same issue on a project. I also have a supertable within a matrix block and we also use locales (but only one is active in this section). I have a linkit field (https://github.com/fruitstudios/LinkIt) in the supertable, which causes me the issue.

When I edit a page with the matrix > supertable > linkit combo it stores my changes, but when I open up the entry page again some values are gone. The linkit field still has the value that I choose to link to an entry (dropdown) but lost the actual selected entry.

Cheers.

**Comment by engram-design** [comment] 2015-11-18 00:05
No news yet I'm afraid, but it's something I will start to have a look at properly. Its a bit of a tricky one to test, but I'll make sure this is fixed very soon.

**Comment by slelorrain** [comment] 2016-02-15 16:35
Hello, do you have any news concerning this issue? 

I have a supertable within a matrix, and also see that Craft doesn't copy the fields from the original locale to the alternate.

Thanks

**Comment by Moorst** [comment] 2016-08-11 09:29
Came here looking to use SuperTable as my LinkIt fields are breaking since I've added locales to my site. Has this issue been resolved for SuperTable or do I need to continue looking for another solution?

**Comment by JonnyTurnerUK** [comment] 2016-08-12 11:30
+1, found this post as I have the same issue

**Comment by engram-design** [comment] 2016-08-29 12:36
Thanks all for your patience with this issue. @hudakdidit I might refer back to your original issue. I've learnt a lot about nested field translations after this exercise, and nested field localisation is a little complex in Craft. I've noticed native Matrix fields have the same issue.

I've found a workaround for this where you disable localisation on the Super Table or Matrix field, and only allow localisation for child fields. Out of interest - is there a benefit to localising a parent field when all content is contained in child fields? As such, the important information that needs to be localised resides in child fields.

For example, refer to the below screenshot of a Super Table > Matrix setup. Notice only the inner field is the only field marked as translatable. Note - that screenshot shows the new settings layout available in 1.0.0.

![screencapture-craft25-craft-dev-office-settings-fields-edit-1357-1472474051542](https://cloud.githubusercontent.com/assets/1221575/18051617/fc276ca4-6e38-11e6-849f-411fb77a7bd7.png)

**Comment by cole007** [comment] 2017-12-07 13:36
Having problems with using locales on a site using Super Tables pretty extensively.
It seems a bit hit and miss regarding which content is copied across and a task to Resave Elements gets stuck migrating SuperTable content across

**Comment by engram-design** [comment] 2018-02-20 10:40
@cole007 I wonder if thats more an environment, or memory issue, particularly with the stalled task?

**Comment by engram-design** [comment] 2020-07-27 10:21
Closing due to age/Craft 2.

**Closed by engram-design** 2020-07-27 10:21 UTC
Labels: craft2
