### ISSUE TITLE
Deleting locales also wipes SuperTable content

### ISSUE THREAD

**Issue by chasegiunta** [verbb/super-table#111] opened 2017-08-29 15:47 UTC
This may be out of the control of SuperTable, but upon removing locales, and transferring content to a new locale (asked by Craft upon removing), the SuperTable content that was associated with the prior locale was completely wiped. The SuperTable was not a translatable field. The intended behavior would be, just as Matrix fields do, edit content records to use the applicable or default locale.

**Comment by groe** [comment] 2018-03-08 15:58
Had the same problem when converting a single-locale site to a multi-locale one, including transferring all entries to a new locale and deleting the old default locale.

I was able to recover the super table contents by restoring an old version for each entry via the UI, so it seems like the issue is that the `craft_supertablecontent_...` tables are not properly updated when transferring entries to a different locale in the locale deletion dialog.

**Comment by engram-design** [comment] 2020-07-27 10:21
Closing due to age/Craft 2.

**Closed by engram-design** 2020-07-27 10:21 UTC
Labels: bug, craft2
